### ISSUE TITLE
Broken link in sf12.Rd

### ISSUE THREAD

**Issue by gillesdutilh** [lbraglia/lbscorer#1]
Dear developer, I just ran into a dead link in the help file for sf12. 
The current link to the origin of the procedure is:
http://crc.marionegri.it/qdv/index.php?page=sf12
However, I think the right link is:
https://lsi.marionegri.it/qdv/index.php?page=sf12

I think the same issue (crc instead of lsi) is in the help of sf36.

**Comment by lbraglia** [comment]
Thanks, fixed
